package com.java.main;

//======================================================
//Source code generated by jvider v1.8.1 UNREGISTERED version.
//http://www.jvider.com/
//======================================================
import javax.swing.JDialog;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.JToolBar;
public class FileEncoder extends JDialog {
	static FileEncoder theFileEncoder;

	class mainPanel extends JPanel implements ActionListener {
		JButton StartButton;
		JButton ExitButton;
		JLabel FunctionalityLabel;
		JComboBox FunctionComboBox;
		JButton Select_Stream;
		JTextField file_path_field;
		JTextField Secret_Key;
		JLabel secret_key_label;
		
		JMenuBar menuBar;
		JMenu fileMenu;
		JMenu helpMenu;
		JMenuItem aboutManuItem;

		public mainPanel() {
			super();
			setSize(600, 600);
			setBorder(BorderFactory.createTitledBorder("Encoder"));

			GridBagLayout gbmainPanel = new GridBagLayout();
			GridBagConstraints gbcmainPanel = new GridBagConstraints();
			setLayout(gbmainPanel);

			StartButton = new JButton("Start");
			StartButton.addActionListener(this);
			gbcmainPanel.gridx = 12;
			gbcmainPanel.gridy = 18;
			gbcmainPanel.gridwidth = 1;
			gbcmainPanel.gridheight = 1;
			gbcmainPanel.fill = GridBagConstraints.BOTH;
			gbcmainPanel.weightx = 1;
			gbcmainPanel.weighty = 0;
			gbcmainPanel.anchor = GridBagConstraints.EAST;
			gbmainPanel.setConstraints(StartButton, gbcmainPanel);
			add(StartButton);

			ExitButton = new JButton("Quit");
			ExitButton.addActionListener(this);
			gbcmainPanel.gridx = 16;
			gbcmainPanel.gridy = 18;
			gbcmainPanel.gridwidth = 1;
			gbcmainPanel.gridheight = 1;
			gbcmainPanel.fill = GridBagConstraints.BOTH;
			gbcmainPanel.weightx = 1;
			gbcmainPanel.weighty = 0;
			gbcmainPanel.anchor = GridBagConstraints.NORTH;
			gbmainPanel.setConstraints(ExitButton, gbcmainPanel);
			add(ExitButton);

			FunctionalityLabel = new JLabel("Select Functionality :");
			gbcmainPanel.gridx = 2;
			gbcmainPanel.gridy = 3;
			gbcmainPanel.gridwidth = 2;
			gbcmainPanel.gridheight = 1;
			gbcmainPanel.fill = GridBagConstraints.BOTH;
			gbcmainPanel.weightx = 1;
			gbcmainPanel.weighty = 1;
			gbcmainPanel.anchor = GridBagConstraints.NORTH;
			gbmainPanel.setConstraints(FunctionalityLabel, gbcmainPanel);
			add(FunctionalityLabel);

			String []dataFunctionComboBox = {"Encode","Decode"};
			FunctionComboBox = new JComboBox(dataFunctionComboBox);
			gbcmainPanel.gridx = 7;
			gbcmainPanel.gridy = 3;
			gbcmainPanel.gridwidth = 1;
			gbcmainPanel.gridheight = 1;
			gbcmainPanel.fill = GridBagConstraints.BOTH;
			gbcmainPanel.weightx = 1;
			gbcmainPanel.weighty = 0;
			gbcmainPanel.anchor = GridBagConstraints.NORTH;
			gbcmainPanel.insets = new Insets(0,2,0,2);
			gbmainPanel.setConstraints(FunctionComboBox, gbcmainPanel);
			add(FunctionComboBox);

			Select_Stream = new JButton("   Select Stream :");
			gbcmainPanel.gridx = 2;
			gbcmainPanel.gridy = 8;
			gbcmainPanel.gridwidth = 1;
			gbcmainPanel.gridheight = 1;
			gbcmainPanel.fill = GridBagConstraints.BOTH;
			gbcmainPanel.weightx = 1;
			gbcmainPanel.weighty = 1;
			gbcmainPanel.anchor = GridBagConstraints.NORTH;
			gbcmainPanel.insets = new Insets(0,6,0,0);
			gbmainPanel.setConstraints(Select_Stream, gbcmainPanel);
			add(Select_Stream);

			file_path_field = new JTextField();
			gbcmainPanel.gridx = 7;
			gbcmainPanel.gridy = 8;
			gbcmainPanel.gridwidth = 10;
			gbcmainPanel.gridheight = 2;
			gbcmainPanel.fill = GridBagConstraints.BOTH;
			gbcmainPanel.weightx = 1;
			gbcmainPanel.weighty = 0;
			gbcmainPanel.anchor = GridBagConstraints.NORTH;
			gbmainPanel.setConstraints(file_path_field, gbcmainPanel);
			add(file_path_field);

			Secret_Key = new JTextField();
			gbcmainPanel.gridx = 7;
			gbcmainPanel.gridy = 14;
			gbcmainPanel.gridwidth = 9;
			gbcmainPanel.gridheight = 1;
			gbcmainPanel.fill = GridBagConstraints.BOTH;
			gbcmainPanel.weightx = 1;
			gbcmainPanel.weighty = 0;
			gbcmainPanel.anchor = GridBagConstraints.NORTH;
			gbmainPanel.setConstraints(Secret_Key, gbcmainPanel);
			add(Secret_Key);

			secret_key_label = new JLabel("   Secret Key :");
			gbcmainPanel.gridx = 2;
			gbcmainPanel.gridy = 14;
			gbcmainPanel.gridwidth = 2;
			gbcmainPanel.gridheight = 1;
			gbcmainPanel.fill = GridBagConstraints.BOTH;
			gbcmainPanel.weightx = 1;
			gbcmainPanel.weighty = 1;
			gbcmainPanel.anchor = GridBagConstraints.WEST;
			gbcmainPanel.insets = new Insets(0,10,0,0);
			gbmainPanel.setConstraints(secret_key_label, gbcmainPanel);
			add(secret_key_label);

			menuBar = new JMenuBar();
			fileMenu = new JMenu("File");
			fileMenu.addActionListener(this);
			helpMenu = new JMenu("Help");
			helpMenu.addActionListener(this);
			aboutManuItem = new JMenuItem("About");
			aboutManuItem.addActionListener(new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) {
					JOptionPane.showMessageDialog(null, "Encoder and Decoder Tool. \n Created and maintained by Tamal Das");
				}
			});
			helpMenu.add(aboutManuItem);
			menuBar.add(fileMenu);
			menuBar.add(helpMenu);
			menuBar.setMargin(new Insets(0,0,0,0));
			setResizable(true);
			gbcmainPanel.gridx = 0;
			gbcmainPanel.gridy = 0;
			gbcmainPanel.gridwidth = 3;
			gbcmainPanel.gridheight = 1;
			gbcmainPanel.fill = GridBagConstraints.BOTH;
			gbcmainPanel.weightx = 1;
			gbcmainPanel.weighty = 0;
			gbcmainPanel.anchor = GridBagConstraints.NORTH;
			gbcmainPanel.insets = new Insets(10,10,10,10);
			gbmainPanel.setConstraints(menuBar, gbcmainPanel);
			add(menuBar);
		} 

		public void actionPerformed(ActionEvent e) {
			if (e.getSource() == StartButton) {
				//Action for StartButton
			}
			if (e.getSource() == ExitButton) {
				//Action for ExitButton
			}
			if (e.getSource() == menuBar) {
				//Action for toolBar
			}
			if(e.getSource() == Select_Stream) {
				
			}
		} 
	} 

	mainPanel mainPanel;
	public static void main(String args[]) {
		try {
			UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
		}
		catch (ClassNotFoundException e) {
		}
		catch (InstantiationException e) {
		}
		catch (IllegalAccessException e) {
		}
		catch (UnsupportedLookAndFeelException e) {
		}
		theFileEncoder = new FileEncoder();
	} 

	public FileEncoder() {
		super();
		//super(OWNER,"TITLE",MODAL);

		mainPanel = new mainPanel();

		setDefaultCloseOperation(DISPOSE_ON_CLOSE);

		setContentPane(mainPanel);
		pack();
		setVisible(true);
	} 
} 

